name: Publish to npm

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Upgrade NPM
        run: npm install -g npm@latest
          

      - name: Install FFmpeg
        run: sudo apt-get update -qq && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Build (ESM + CJS)
        run: npm run build

      - name: Units Test
        run: npm run test:unit

      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ""
